spring:
  application:
    name: aoi

# 自定义 info 信息，对应 management.info.env
info:
  welcome: "開発者さん、お疲れさまです"

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
