spring:
  application:
    name: aoi

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
